### ISSUE TITLE
Help with heroku build

### ISSUE THREAD

**Issue by lorinma** [ihuston/python-conda-buildpack#4]
Hi,

I'm trying to use this buildpack on heroku. Although the app was deployed, but it doesn't running correctly like in localhost.And the build log shows some suspect errors in installing conda packages.

May I ask to give some advice?

Thanks!

build log:
-----> Fetching set buildpack https://github.com/ihuston/python-conda-buildpack.git... done
-----> Python app detected
-----> Starting compile step...
-----> Preparing Python Environment...
-----> Installing Dependencies...
/tmp/buildpack20151221-156-1f82oz4/bin/compile: line 58: /tmp/build_986ec6a3f149f7305826c34692e08690/lorinma-ifc2mongo-267f3e6/.conda/bin/conda: No such file or directory
/tmp/buildpack20151221-156-1f82oz4/bin/compile: line 59: /tmp/build_986ec6a3f149f7305826c34692e08690/lorinma-ifc2mongo-267f3e6/.conda/bin/conda: No such file or directory
-----> Installing conda environment from environment.yml...
/tmp/buildpack20151221-156-1f82oz4/bin/compile: line 66: /tmp/build_986ec6a3f149f7305826c34692e08690/lorinma-ifc2mongo-267f3e6/.conda/bin/conda: No such file or directory
/tmp/buildpack20151221-156-1f82oz4/bin/compile: line 78: /tmp/build_986ec6a3f149f7305826c34692e08690/lorinma-ifc2mongo-267f3e6/.conda/bin/conda: No such file or directory
-----> Fixing paths...
sed: no input files
-----> Finished compile step
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing... done, 6K
-----> Launching... done, v8
       https://ifc2mongo.herokuapp.com/ deployed to Heroku

environment.yml:
name: ifc2mongo
channels:
    - lorinma
    - DLR-SC
dependencies:
- ifcopenshell=0.5dev=py35_0
- pip:
  - Flask-PyMongo==0.4.0
  - Flask-RESTful==0.3.5
  - requests==2.9.0
  - gunicorn

**Comment by ihuston** [comment]
Hi lorinma,

This buildpack is not designed to work with Heroku and includes Cloud Foundry specific changes.

You might have better luck using this Heroku buildpack for conda: https://github.com/kennethreitz/conda-buildpack
