### ISSUE TITLE
how to use "bokeh serve" in cloud foundry?

### ISSUE THREAD

**Issue by charleywan2004** [ihuston/python-conda-buildpack#5]
Do you have a buildpack which has "bokeh"? 

I use "flask" and "bokeh" to program a server. Do you have an example to deploy "flask" and "bokeh" to cloud foundry?

**Comment by ihuston** [comment]
Hi charleywan2004, 

This buildpack doesn't include specific packages, but instead provides a mechanism to list these dependencies for installation when the app droplet is being built.

You can specify the python packages to install for your app by using either a requirements.txt file or a conda environment.yml file.

In this case you might have the following in your requirements.txt:

flask
bokeh
